### PR TITLE
Hover delete buttons for genes in the DNA component.

### PR DESCRIPTION
**Pull request by chrisharrington**
This change is [Reviewable](https://reviewable.io/reviews/storyshop/app/121)

### CODE REVIEW

**Review by joshdmiller — CHANGES_REQUESTED** [review]
I do feel the `style` block is a little hacky. It may make sense to use something like Radium, but unfortunately, it will not work with stamps because Radium requires use of the `new` keyword. This is not stampit's fault, but may be a reason to move away from it (what good is "better" if it's incompatible with so much of the ecosystem?).

So I'll leave the judgment to you: skip the stamps on the components that have style needs that surpass what we can easily do with inline styles, so we can use Radium; or use JavaScript events.

Also, the function signature for the delete event isn't quite right; I should have been clearer in this issue, but #89, which is part of the same epic, shows the function signature.

**Comment by chrisharrington** [comment]
@joshdmiller Looks as though the `deleteGene` prop should be called with `character_id` and `index`. Is that right? If so, does `gene` contain a character ID?

Also, I chose to go with javascript events here. Radium works pretty well when the hover trigger is the element being affected by the hover style, but falls down a little when they differ, apparently.

**Comment by chrisharrington** [comment]
@joshdmiller Wanna take a look at this? Thanks!

**Comment by joshdmiller** [comment]
> Looks as though the deleteGene prop should be called with character_id and index. Is that right? If so, does gene contain a character ID?

It gets called with the id of the character and an index, but the gene does not contain a character ID. The value is stored in mongo as a literal array and returned as such. That may change in the future, but for now it's fine. So there is no need for a character ID in the gene.

Can you add the footer and rebase? Thanks!

**Comment by chrisharrington** [comment]
@joshdmiller Footer added.

**Review by joshdmiller — APPROVED** [review]

**Pull request merged**
