### PR TITLE
chore(gitignore): add npm-debug.log to .gitignore

### PR DESCRIPTION
**Pull request by sethmerrick**

### CODE REVIEW

**Comment by joshdmiller** [comment]
This is definitely a matter of opinion, but here's my thinking. `npm-debug.log` is an exception case, rather than a file we expect to be generated as part of the app's build or execution. One _could_ argue that we wouldn't want to add such "random" files to `.gitignore` because the file is not generated by app design. I'll leave it up to you.

FWIW, you can also have a global git ignore file that you can set with whatever you want to omit files such as this. For example, I use [this one](https://github.com/joshdmiller/dot-files/blob/master/home/gitignore_global), which I [add to my gitconfig](https://github.com/joshdmiller/dot-files/blob/master/home/gitconfig#L8)[1] to ignore undo and swap files created by Vim.

[1]: Also `git config --global core.excludesfile  /path/to/global-gitignore`

**Comment by joshdmiller** [comment]
Also be sure to merge manually, so we don't get the merge commit: https://github.com/StoryShop/app/commits/master

**Comment by sethmerrick** [comment]
Thank you for the thorough explanation!
- I thought `npm-debug.log` was likely a good candidate for the global `.gitignore`, and am glad to have a clearer understanding of _why_.
- D'oh! You did such an excellent job of explaining the hows & whys of avoiding the blasted merge commit, and there I went ballsing it up the very first try. :neutral_face: I'll get it right next time.

**Comment by sethmerrick** [comment]
Ha, I hadn't yet made it to the line of [https://gist.github.com/joshdmiller/dd1a0cc40e06f1aa47c7](https://gist.github.com/joshdmiller/dd1a0cc40e06f1aa47c7) that states plain as day: 

> When pull requests are ready to be merged, the "Merge" button on GitHub should __never__ be used.

 when I enthusiastically hit the giant green button in reply to the thumbs-up. :) Live & learn.

**Pull request closed without merging**
