### PR TITLE
style(app-bar): change color of world settings app bar

### PR DESCRIPTION
**Pull request by sethmerrick**
Though the teal is a bit too close to the blue & green, I felt the blueGrey was a bit too far from them.

### CODE REVIEW

**Comment by joshdmiller** [comment]
The PR looks good to me, but to use teal for settings I think we'll have to change the elements colour too. In the sidenav, they look really close:

storyshop-teal

**Comment by sethmerrick** [comment]
Ah, I mistakenly thought that sidebar link would be disappearing in favor of the fleshed-out block at the top of the left drawer for World stuff.

If the World Settings link will remain in the left drawer, I agree the teal may be too close to the green. The MD palette seems to lend itself well to groups of 3 cool vibrant colors; not so much 4. To get a 4th in the set, I have to pull from the red/yellow/orange, which feels too hot, or a flat color like brown/blueGrey... will continue to look for a solution.

**Comment by joshdmiller** [comment]
I had planned to put the fleshed out block above the current set of links
in the sidenav. When switching worlds in the sidenav, I don't think it
should close the sidenav to the world home/settings page because that's not
the common use case. So the only link would be the one we have now,
unfortunately. The "world picker" would really just change the sidenav
header and the place to which the visible links point.

fwiw, I don't think red/yellow/orange are too hot nor that blue-grey or
grey are too dull (though I think brown is too dull). But it's worth more
thought.

**Comment by sethmerrick** [comment]
Thanks for 'splaining your thoughts on it. I agree, and think it's not a priority to give it any further attention at present. Closing PR.

**Pull request closed without merging**
