### PR TITLE
Label chooser component

### PR DESCRIPTION
**Pull request by chrisharrington**
#101.

---

This change is [Reviewable](https://reviewable.io/reviews/storyshop/app/119)

### CODE REVIEW

**Review by joshdmiller — CHANGES_REQUESTED** [review]
Looks pretty good, but the `onChange` callback signature doesn't match the spec. Should be ID and new label, but instead is an object.

**Comment by chrisharrington** [comment]
@joshdmiller Whoops. Missed that. Fixed.

**Review by joshdmiller — APPROVED** [review]

**Comment by joshdmiller** [comment]
This is missing the commit footer. Can you add that and rebase against master? Thanks!

**Comment by chrisharrington** [comment]
@joshdmiller Fixed the commit message.

**Pull request merged**
